const BOREDOM_IDEAS = [
  "Narrate your refrigerator's contents like a nature documentary. The leftover pizza is the apex predator of the middle shelf ecosystem.",
  "Write a formal complaint letter to your socks about their chronic disappearance problem. Demand answers about where the missing ones go.",
  "Create an elaborate backstory for the oldest item in your junk drawer. It was clearly once owned by a Victorian ghost hunter.",
  "Hold a knighting ceremony for your most reliable pen using a ruler as a sword. It has served the realm of your to-do lists faithfully.",
  "Practice your Oscar-worthy gasp for when someone tells you mildly surprising news. The grocery store is out of your favorite cereal? GASP.",
  "Write a Yelp review for your shower's water pressure. Be brutally honest about its inconsistent temperature policies.",
  "Invent a product that solves a problem nobody has. Behold: the left-handed soup spoon with built-in existential crisis detection.",
  "Take an imaginary vacation to the land behind your couch. Document the strange artifacts and dust bunny civilizations you discover.",
  "Host a competitive speed-folding championship with your laundry. The fitted sheet round is always controversial.",
  "Have a philosophical debate with yourself about whether a hot dog is a sandwich. Present arguments from both the pro and anti factions.",
  "Conduct a covert surveillance mission on your houseplant. It's been suspiciously quiet lately, and you don't trust its photosynthesis alibi.",
  "Write the fictional history of your street as if it were once the capital of an ancient empire of squirrels.",
  "Perform a mock academic study on the optimal angle for leaning against kitchen counters. Publish your findings to no one.",
  "Practice your acceptance speech for winning 'Most Average Human of the Year.' Thank your bed for always being there.",
  "Build a tiny apartment complex for dust mites using matchboxes. Include a rooftop pool made from a bottle cap.",
  "Commentate your own breakfast preparation like it's the final round of an intense cooking competition. The stakes have never been higher for this toast.",
  "Draft a peace treaty between your left and right feet. They've been stepping on each other's territory for too long.",
  "Create a museum exhibit featuring your collection of expired coupons. Each one tells a story of missed savings.",
  "Perform a sacred ritual to appease the WiFi gods when your connection is slow. The router demands offerings of unplugging and replugging.",
  "Practice delivering the news that you've eaten all the cookies with maximum dramatic gravitas. This is truly a dark day.",
  "Rate and review each of your forks on a ten-point scale. The one with the slightly bent tine gets marked down for attitude.",
  "Design a revolutionary product: a calendar that only shows days you feel like acknowledging. Mondays are permanently optional.",
  "Explore the exotic destination known as 'under your bed.' Marvel at the dust ecosystems and mysterious sock colonies.",
  "Challenge yourself to a staring contest with a photo of yourself. First one to blink buys dinner (you always lose).",
  "Host a symposium with your stuffed animals debating whether the floor is actually lava. Present peer-reviewed evidence.",
  "Pretend you're a spy whose mission is to make a sandwich without alerting the sleeping cat. Failure is not an option.",
  "Document the rise and fall of the Great Junk Drawer Empire through interpretive drawer slamming and dramatic narration.",
  "Conduct a peer review of your own life choices as if they were a disappointing academic paper. Revisions recommended.",
  "Write an emotional thank-you speech for your pillow, acknowledging all the nights it absorbed your drool without complaint.",
  "Construct a scale model of Stonehenge using TV remotes. Ancient druids would definitely approve of your channel-changing monument.",
  "Provide live sports commentary for your cat cleaning itself. That's an aggressive move on the left ear - the judges will score that highly!",
  "Compose a formal letter to Future You, warning them about that weird smell in the fridge you're choosing to ignore today.",
  "Develop an origin story for the stain on your favorite shirt. It was clearly caused by a radioactive burrito with trust issues.",
  "Hold a retirement ceremony for a pen that has finally run out of ink. It gave everything it had to your grocery lists.",
  "Perfect your reaction for when someone reveals they've never seen your favorite movie. Channel both betrayal and missionary zeal.",
  "Write a scathing restaurant review for your own cooking. The ambiance was questionable and the chef seemed distracted by their phone.",
  "Patent a completely useless invention: self-peeling bananas that only work on Tuesdays during full moons.",
  "Lead an expedition through the treacherous terrain of your closet. Many socks have entered, few have returned as matching pairs.",
  "Organize a tournament to determine which of your mugs holds coffee with the most dignity. There can only be one champion.",
  "Argue passionately about whether 11:59 AM or 12:01 PM is the true start of afternoon. This debate has raged for generations.",
  "Establish a surveillance network of sticky notes to monitor your houseplant's suspicious activities. Trust no one, especially the fern.",
  "Chronicle the history of your kitchen sponge as if it were a legendary warrior who has seen too many dishes to count.",
  "Submit your sleeping habits for formal academic peer review. Results: inconclusive but concerning.",
  "Rehearse your victory lap for successfully parallel parking on the first try. This moment deserves a standing ovation.",
  "Engineer a tiny transit system for ants using straws and bottle caps. Include a tiny 'Mind the Gap' sign.",
  "Announce your trip to the bathroom like a nature show host tracking rare wildlife. And here we observe the creature in its natural habitat.",
  "Negotiate a non-aggression pact between your phone charger and the outlet. They've had their differences, but peace is possible.",
  "Curate an art gallery of your most questionable fashion choices from old photos. Each piece deserves a pretentious description.",
  "Conduct a solemn ceremony to honor the brave leftovers who didn't make it before the expiration date. They served us well.",
  "Train yourself to deliver 'I told you so' with such subtle grace that people actually thank you for it.",
  "Critique each of your towels on their absorbency, texture, and overall life choices. The beach towel has potential.",
  "Introduce to market: shoes that make different cartoon sound effects with each step. Finally, walking is entertaining.",
  "Navigate the mystical realm inside your car's glove compartment. Legend speaks of ancient napkins and mysterious insurance cards.",
  "Host an Olympics where you compete against yourself from yesterday. Today-you versus yesterday-you: who will prevail?",
  "Lead a heated philosophical inquiry into why we park on driveways and drive on parkways. The universe demands answers.",
  "Deploy your collection of expired gift cards as undercover agents. Their mission: to remind you of past shopping failures.",
  "Recount the epic saga of how that one rubber band ended up in your kitchen drawer. It's a tale of resilience.",
  "Defend your thesis on the aerodynamics of poorly thrown paper airplanes. Your research spans decades of failure.",
  "Compose your hall of fame induction speech for achieving inbox zero that one time in 2019. You'll never forget that day.",
  "Construct a miniature ski resort for your fingers using books and tissues. The bunny slope is a gentle incline of your arm.",
  "Provide blow-by-blow commentary of your attempt to find matching Tupperware lids. This is the championship round, folks.",
  "Author a stern memo to your brain about its 3 AM thought policy. These meetings need to be scheduled during business hours.",
  "Develop the tragic backstory of the single glove you found on the sidewalk. It's searching for its soulmate.",
  "Preside over a formal decommissioning ceremony for batteries that might still have some juice left. We can never know for sure.",
  "Master the art of reacting to someone telling you their name when you've already forgotten it twice. Nod knowingly.",
  "Review each of your pillows as if they were luxury hotels. The flat one gets two stars for trying its best.",
  "Prototype socks that verbally protest when you put them on inside out. They have opinions and they will share them.",
  "Trek through the legendary canyon between your couch cushions. Many coins have fallen here, never to return.",
  "Create an eating competition where you race yourself to finish a snack. You always win, but also always lose.",
  "Engage in rigorous academic discourse about whether cereal with milk is technically a soup. Defend your position with vigor.",
  "Recruit your shoes as double agents in a complex spy network. The left sneaker's loyalty is questionable at best.",
  "Compose a sweeping historical epic about the founding of the nation of your bedroom. Independence was declared at age twelve.",
  "Peer review your own handwriting as if it were a controversial scientific manuscript. Results: mostly illegible.",
  "Accept an invisible Grammy for best humming performance in a shower. The acoustics really made the difference.",
  "Design a tiny outdoor cinema for insects using your phone and a tissue box. Tonight's feature: a nature documentary (ironic).",
  "Deliver play-by-play coverage of your phone charging. It's at 47%, folks, and the tension is absolutely electric.",
  "Write a heartfelt letter to your past self about the drawer you still haven't organized. We both know the truth.",
  "Trace the ancestry of your favorite mug back to its probable life as a humble lump of clay. What a journey.",
  "Organize a candlelit vigil for the dreams you forgot immediately upon waking. They had such potential.",
  "Rehearse being surprised by a surprise party so convincingly that you almost fool yourself. It's an art form.",
  "Judge each of your houseplants on their commitment to photosynthesis. The succulent is clearly slacking off.",
  "Design a groundbreaking new umbrella that only works when you're already inside. Revolutionary lack of functionality.",
  "Explore the untamed wilderness of your bag's bottom. Discover civilizations of crumbs and fossilized receipts.",
  "Compete against your reflection in a series of nonsensical athletic events. Neither of you ever loses or wins.",
  "Host a spirited debate about whether invisible means see-through or simply not present. The distinction matters.",
  "Send your collection of dead pens on a reconnaissance mission. Report back on where all the ink really goes.",
  "Write the unauthorized biography of your couch, detailing its scandalous history of supporting various bottoms.",
  "Present your research findings on the science of procrastination tomorrow. Or maybe the next day. We'll see.",
  "Deliver a stirring speech accepting the Nobel Prize for your groundbreaking work in snack retrieval.",
  "Construct a tiny beach resort for your toes using sand-colored fabric and a desk lamp for the sun.",
  "Narrate your search for the TV remote like an increasingly desperate survival documentary. Day three: hope fades.",
  "Draft a formal apology to your houseplants for all the times you forgot to water them. They deserved better.",
  "Create a detailed origin story for the mysterious sticky spot on your kitchen counter. It was born of jam, probably.",
  "Host a medal ceremony for the oldest items in your pantry. They've survived multiple kitchen cleanings.",
  "Perfect the art of looking deeply concerned about minor inconveniences. The coffee maker is making a weird noise.",
  "Submit reviews for various walls in your home based on their load-bearing personality and aesthetic choices.",
  "Invent a revolutionary device that tells you exactly which light switch controls which light. The future is now.",
  "Lead an anthropological expedition through the artifacts in your medicine cabinet. Some of these date back to previous tenants.",
  "Establish a league where you compete to see who can make the bed faster: you or also you. Track your records.",
  "Philosophically examine whether a straw has one hole or two. Prepare for the argument to consume your afternoon.",
  "Recruit your bookmarks as sleeper agents in an elaborate literary espionage operation. The bookmark in the cookbook is compromised.",
  "Document the legendary migration patterns of your keys from one surface to another. Science demands answers.",
  "Conduct an internal audit of your own opinions, rating each on a scale of 'absolutely right' to 'suspiciously baseless.'",
  "Prepare your emotional acceptance speech for winning the award for Most Convincing Fake Sick Voice.",
  "Build a tiny observatory for imaginary astronomers using toilet paper tubes. Tonight they'll discover a new ceiling constellation.",
  "Provide running commentary on yourself trying to open a stubborn jar lid. The struggle is real and riveting.",
  "Compose a peace accord between your alarm clock and your desire to sleep. Neither party is satisfied.",
  "Develop a cinematic universe for the random objects on your desk. The stapler is clearly the reluctant hero.",
  "Hold a state funeral for the last sheet of your notepad. It gave its life for your grocery list.",
  "Cultivate the dramatic pause you deploy before giving your order at a restaurant. Let them wait.",
  "Write detailed restaurant-style reviews for each of the leftovers currently in your fridge. The pasta shows promise.",
  "Design revolutionary shoes that make your footsteps completely silent until you're trying to sneak. Then: maximum volume.",
  "Chart an expedition through the exotic locale of your neighbor's yard, as seen from your window. Fascinating creatures roam there.",
  "Host a speed-stacking competition using whatever's already on your counter. The spice jars versus the canned goods.",
  "Contemplate deeply whether you can stand backwards on stairs. Present your findings to an indifferent audience.",
  "Task your collection of spare buttons with infiltrating the local sewing kit. Their mission is classified.",
  "Compose the oral history of your family's tradition of losing the scissors in increasingly absurd places.",
  "Formally peer review your own internet search history. Methodology: questionable. Ethics: declined to comment.",
  "Prepare your remarks for receiving a Lifetime Achievement Award in opening the fridge hoping something new appeared.",
  "Construct miniature ski lifts for cotton balls using dental floss and popsicle sticks. Bunny hill opens at noon.",
  "Deliver play-by-play analysis of paint drying with the intensity of a championship finals announcer. Edge-of-seat stuff.",
  "Write a formal request to your brain asking why it keeps playing that one song on repeat. Cease and desist.",
  "Develop a sprawling backstory for the unidentified stain on your ceiling. It clearly involves a previous tenant and betrayal.",
  "Preside over graduation ceremonies for socks that have survived an entire year without getting holes. They made it.",
  "Practice your reaction for when someone spoils a show you weren't even watching. Betrayal must be conveyed precisely.",
  "Submit for peer review your system of organizing things by putting them in a pile. Publish or perish.",
  "Write a stirring nomination speech for your vacuum cleaner to join the appliance hall of fame. It sucks, in the best way.",
  "Engineer tiny zip lines for action figures using string and a sloped surface. Adventure awaits the brave.",
  "Commentate your own blinking like it's an intensely competitive sport. And there's the flutter - controversial form!",
  "Draft a treaty between your body and your brain about reasonable bedtime expectations. Terms are still being negotiated.",
  "Curate a gallery showing of dust bunnies collected from under your furniture. Each is titled and priced accordingly.",
  "Conduct initiation rites for new items entering your junk drawer. They must prove their worthlessness.",
  "Train yourself to react to 'we need to talk' without immediately assuming the worst. Progress may be slow.",
  "Rate every light switch in your home based on click satisfaction and response time. The bathroom one is subpar.",
  "Invent a pillow that gets cold again every time you flip it. Billions of dollars await.",
  "Journey through the forgotten wasteland inside your vacuum cleaner bag. Archaeological treasures await discovery.",
  "Host a staring contest with objects around your house. The wall is undefeated and slightly smug about it.",
  "Explore whether 'nothing' is technically 'something' since we gave it a name. Philosophy majors, assemble.",
  "Establish your house plants as an intelligence network reporting on the activities of dust particles.",
  "Write the epic poem recounting the great USB cord tangle of this morning. Hercules faced lesser trials.",
  "Defend your doctoral thesis on the optimal temperature for drinking water. Your committee is unimpressed.",
  "Write an emotional hall of fame speech for the pan that's outlasted three relationships.",
  "Build tiny hammocks for your fingers using tissues and rubber bands. They've earned this vacation.",
  "Provide urgent breaking news coverage of your attempt to assemble IKEA furniture. Casualties: your patience.",
  "Author a strongly-worded letter to whichever ancestor decided we should fold fitted sheets. We need to talk.",
  "Create an elaborate mythology around why one cabinet door never closes properly. It's haunted, obviously.",
  "Organize formal retirement proceedings for your oldest pair of underwear. Thank them for their service.",
  "Perfect your look of mild interest for stories you've heard seventeen times. The eyebrow raise is key.",
  "Review your various yawns, ranking them by length, intensity, and contagiousness. The 3 PM yawn reigns supreme.",
  "Design a revolutionary product: a snooze button that actually buys you quality sleep. Take my money.",
  "Mount an expedition to locate the source of that weird smell in your kitchen. It could be anywhere.",
  "Compete against gravity to keep your eyes open during a boring meeting. Gravity usually wins.",
  "Debate whether you can technically 'be yourself' when yourself is constantly changing. Get existential.",
  "Deploy your collection of mystery keys as secret agents. None of them remember what they unlock.",
  "Chronicle the territorial disputes between your refrigerator items. The cheese bloc is expanding aggressively.",
  "Conduct a formal study on why your phone charger only works at one angle. Submit findings to Science Magazine.",
  "Prepare remarks for receiving an honorary degree in finding things right after giving up the search.",
  "Construct a tiny town for microorganisms using crumbs and droplets of water. You are their benevolent mayor.",
  "Provide the documentary voiceover for your own trip to the bathroom at 2 AM. Danger lurks in the darkness.",
  "Write an emotional farewell letter to your patience before logging onto social media.",
  "Develop complete character profiles for each of your hangers. The wire one has a troubled past.",
  "Host an awards ceremony honoring the bravest crumbs who fell behind the stove. They will not be forgotten.",
  "Master the art of sighing so that it conveys exactly how you feel about Mondays without words.",
  "Write Zagat-style reviews for water from different taps in your house. The bathroom sink has notes of rust.",
  "Patent an invention that tells you where you left your keys and also your life direction. Multifunctional.",
  "Explore the ancient ruins of the box of stuff you never unpacked when you moved in. Treasures await.",
  "Establish a competitive circuit for racing yourself from room to room. Your living room time is unbeatable.",
  "Analyze whether a broken clock is right twice a day or wrong 86,398 times. Math is beautiful.",
  "Recruit your spare change as a network of spies embedded in various coat pockets and couch cushions.",
  "Write the official history of the pen cup on your desk, including the civil war between markers and pens.",
  "Defend your controversial thesis on whether water is wet or merely makes things wet. Academic careers are at stake.",
  "Accept an imaginary lifetime achievement award for never learning how to properly fold a burrito.",
  "Build a tiny carnival for ants complete with a Ferris wheel made from a CD and toothpicks.",
  "Narrate your attempt to untangle headphones like it's defusing a bomb in an action movie. The tension!",
  "Compose a passive-aggressive note to yourself about dishes in the sink, then ignore it.",
  "Develop an extended universe for the stickers you've been accumulating but never using. Each has a purpose.",
  "Hold a moment of silence for all the clever comebacks you thought of too late. Gone but not forgotten.",
  "Refine your technique for looking busy when someone walks by. The focused squint is essential.",
  "Conduct a thorough review of your own walking style, rating each foot on technique and commitment.",
  "Design a product that reminds you what you came into this room for. Revolutionary memory technology.",
  "Lead a safari through the wilds of your garage or storage space. Document the species you encounter.",
  "Host a series of events pitting your left hand against your right in various household challenges.",
  "Contemplate whether you're living in the past since everything you perceive already happened milliseconds ago.",
  "Establish an undercover operation among your bathroom products. The shampoo has been there too long.",
  "Record the epic tale of how your family's junk drawer became a place of no return.",
  "Present your findings on the aerodynamics of the blanket-to-bed ratio for optimal temperature.",
  "Write your remarks for being inducted into the hall of fame for snooze button expertise.",
  "Construct an elaborate miniature space station for dust mites using household items.",
  "Provide suspenseful narration of your microwave counting down the final seconds. Will it explode? Probably not.",
  "Draft an alliance proposal between you and your future self about not eating all the snacks tonight.",
  "Trace the lineage of every rubber band in your possession back to its original purpose.",
  "Orchestrate a formal coronation ceremony for the remote control. It rules the living room absolutely.",
  "Practice receiving news that your favorite restaurant is closed with appropriate levels of devastation.",
  "Write in-depth analyses of each chip in a bag, rating them by size, shape, and seasoning distribution.",
  "Propose a revolutionary new product: a pen that actually works when you pick it up. The innovation.",
  "Chart a course through the treacherous waters of your bathroom drain. Many hair travelers have perished.",
  "Invent a competitive sport involving only items currently within arm's reach. Establish official rules.",
  "Debate with yourself whether your reflection is copying you or you're copying your reflection.",
  "Commission your dust collection as intelligence operatives tracking air current patterns.",
  "Write the unabridged history of every bookmark currently in your browser, explaining why each survives.",
  "Present a dissertation on the philosophy of 'almost empty' versus 'still some left' regarding containers.",
  "Deliver a rousing speech accepting the award for most creative excuse for not exercising.",
  "Design a tiny library for borrowing insects using matchboxes. Late fees are strictly enforced.",
  "Provide live analysis of clouds passing by your window like they're competing in a beauty pageant.",
  "Author a formal treaty between your work brain and your fun brain about respecting boundaries.",
  "Develop comprehensive backstories for every magnet on your refrigerator. Some have tragic pasts.",
  "Host a ceremony officially retiring the tube of sunscreen from two summers ago. It served its time.",
  "Perfect the art of nodding thoughtfully while actually thinking about what's for dinner.",
  "Critique each doorknob in your home on its turning satisfaction and overall aesthetic contribution.",
  "Create an invention that makes waiting for toast feel exciting. Perhaps a toaster with plot twists.",
  "Lead an expedition into the depths of your sock drawer to reunite separated pairs. Romance awaits.",
  "Host an elimination tournament for your collection of plastic bags stuffed inside other plastic bags.",
  "Philosophize about whether you're standing still or the Earth is rotating under you. Motion is relative.",
  "Assign code names to all your furniture and conduct covert operations between them.",
  "Compile the oral history of every stain on your carpet, passed down through generations of denials.",
  "Write a peer-reviewed paper on the optimal method for arranging pillows you'll just push aside anyway.",
  "Prepare your acceptance speech for winning 'Best Performance in Acting Like You Remember Someone's Name.'",
  "Build tiny ski jumps for paperclips using folded paper. The winter games are coming.",
  "Commentate your own attempts to sit up from lying down without making old person noises. It's a challenge.",
  "Draft a formal complaint to the universe about why yawning is contagious. This is a design flaw.",
  "Create detailed origin stories for the collection of takeout menus you'll never use again.",
  "Hold a candlelight ceremony for all the food that went bad before you could eat it. They had potential.",
  "Master the subtle eye contact that says 'I acknowledge you' without inviting further conversation.",
  "Review and rate your own sighs throughout the day, categorizing them by type and emotional depth.",
  "Invent a device that finds the start of tape rolls instantly. Nobel Prize material.",
  "Navigate the unexplored territory beneath your car seats. Many french fries have made their final home here.",
  "Challenge your past self to predict what present you would be doing. Past you was wildly optimistic.",
  "Explore whether the question 'what came first, the chicken or the egg' applies to breakfast food preferences.",
  "Create a spy network using the loose threads from various clothing items. They're everywhere.",
  "Chronicle the great migration of stuff from your pockets to random surfaces throughout your home.",
  "Submit a research paper on why hitting electronics makes them work temporarily. The science is sound.",
  "Write your speech for receiving a lifetime achievement award in overthinking simple decisions.",
  "Engineer tiny roller coasters for marbles using cardboard tubes and tape. Theme park dreams.",
  "Provide documentary coverage of your houseplant's dramatic journey toward the window for light.",
  "Write a sternly worded letter to autocorrect about ducking up your messages.",
  "Develop a detailed backstory for the oldest item in your medicine cabinet. It has seen things.",
  "Organize a graduation ceremony for expired gift cards who have completed their worthless journey.",
  "Train yourself to deliver 'that's interesting' in a way that sounds genuine even when it's not.",
  "Rate each of your coffee mugs on handle ergonomics, heat retention, and sentimental value.",
  "Propose an invention: a remote control that can't slip between couch cushions. Game-changing.",
  "Lead an archaeological dig through your old email inbox. Ancient embarrassments await discovery.",
  "Create a competitive league for racing dust bunnies across smooth floors. Draft picks are crucial.",
  "Examine whether it's possible to think about nothing, or if thinking about nothing is still something.",
  "Establish your collection of twist ties as a covert resistance movement against bread bag entropy.",
  "Narrate the history of how your family acquired that one weird decoration nobody actually likes.",
  "Complete a formal study on why the other line always moves faster. Your methodology: pure observation.",
  "Practice your acceptance speech for winning the 'Best Excuse for Not Returning a Text Right Away' award.",
  "Construct tiny treehouses for ladybugs using twigs and leaves. Applications are now being accepted.",
  "Provide breaking news updates on your quest to remember why you walked into this room.",
  "Draft a mutual respect agreement between you and the spider in the corner. Neither party is thrilled.",
  "Create origin stories for each of the random cords in your 'just in case' cord box.",
  "Preside over a formal sendoff for the last roll of the toilet paper you forgot to replace.",
  "Develop your range of expressions for when someone shows you photos of their vacation. Interest is key.",
  "Write harsh but fair reviews of each ice cube tray based on pop-out ease and cube uniformity.",
  "Design an app that tells you the exact moment your leftovers transition from 'still good' to 'science experiment.'",
  "Map the unexplored frontiers inside your backpack's smallest pocket. Civilizations of crumbs thrive there.",
  "Organize a tournament to crown which of your pens has the smoothest glide. There can be only one.",
  "Debate with conviction whether waving back at someone who wasn't waving at you is a federal crime.",
  "Deploy your various hair ties as intelligence agents. Most of them have already gone rogue.",
  "Record the legendary tale of how your grandmother's ancient Tupperware became indestructible.",
  "Present peer-reviewed research on why your phone battery drains faster when you need it most.",
  "Compose your speech for being honored as a master of saying 'we should hang out' without follow-through.",
  "Build miniature skate parks for insects using cardboard and tape. Watch the ants shred.",
  "Commentate your own internal debate about whether to take the stairs or the elevator. Riveting analysis.",
  "Write a formal apology to your bank account for the impulse purchases it never asked for.",
  "Develop sprawling narrative universes for each of the abandoned shopping carts you've seen.",
  "Hold a formal intervention for the drawer that won't close properly. It needs help.",
  "Master the facial expression that means 'I'm listening' while your mind explores other dimensions.",
  "Conduct thorough evaluations of each of your phone's app icons based on design and placement dignity.",
  "Create a product that alerts you when you're about to say something you'll regret. Market demand is infinite.",
  "Venture through the lost city of items that fell behind your dresser. Archaeological wonders await.",
  "Host an epic battle between your dominant hand and your weaker hand in tasks they never do.",
  "Consider deeply whether time flies or we fly through time. It's a matter of perspective.",
  "Recruit your various containers without lids as a surveillance team. They've got nothing better to do.",
  "Write the comprehensive history of every address your family has lived at, as remembered incorrectly by everyone.",
  "Present your thesis on the optimal method of eating Oreos. Twist first? Dunk? The debate rages.",
  "Accept your award for excellence in the field of standing in front of the fridge hoping something inspires you.",
  "Design miniature water parks for your fingers using cups, straws, and imagination. Splash Mountain opens soon.",
  "Deliver suspenseful live coverage of your tea steeping to the perfect strength. Seconds matter.",
  "Compose a diplomatic letter to your neighbors about their dog's barking schedule. Suggest appointments.",
  "Create elaborate backstories for every car you can see from your window. Each has a name and dreams.",
  "Host a retirement party for the lightbulb that's been flickering menacingly for weeks. Its time has come.",
  "Perfect the art of looking like you meant to trip. Incorporate a little dance move.",
  "Rate your various doorbell sounds on surprise factor and ability to trigger panic.",
  "Propose a revolutionary new invention: bread that stays fresh forever but still tastes homemade.",
  "Lead an expedition through your old photos on your phone. Past you made some choices.",
  "Create a speed-stacking league using all the empty containers you haven't recycled yet.",
  "Investigate whether 'irregardless' is a word or a collective hallucination. Language is weird.",
  "Commission your collection of grocery bags as a spy ring. They're thin and easily hidden.",
  "Document the epic struggles for territory between items in your freezer. Frost giants rule there.",
  "Submit formal research on why you always pick the slow checkout line. Statistics don't lie.",
  "Write your acceptance remarks for being honored as the world's foremost 'I'll do it later' champion.",
  "Build tiny concert venues for earbuds using tissue boxes. Sound check starts in five.",
  "Provide play-by-play coverage of your attempt to find the end of the packing tape. It's hidden well.",
  "Draft a formal reconciliation agreement between you and your alarm clock. The relationship is strained.",
  "Construct complete mythologies around why your phone charger only works in one specific outlet.",
  "Conduct a formal ceremony to honor the charging cable that's been with you since two phones ago.",
  "Practice your response to 'tell me a fun fact about yourself' until it doesn't sound rehearsed. It always will.",
  "Write reviews of various patches of carpet based on softness, color consistency, and stain resistance.",
  "Invent a device that tells you how much longer you can ignore a task. Procrastination analytics.",
  "Explore the mysterious depths of your coat pockets from last winter. Treasures and old receipts await.",
  "Host a series of matches pitting different ice cubes against each other in melting competitions.",
  "Philosophize about whether your bed misses you when you're gone. It definitely does.",
  "Create an intelligence network among your various bags, purses, and backpacks. Information is power.",
  "Compose the definitive history of your family's relationship with that one Pyrex dish from the '80s.",
  "Conduct a scholarly analysis of why every pen in a cup is either dead or on its last breath.",
  "Prepare your speech for being inducted into the hall of fame for most convincing fake phone calls.",
  "Build tiny ski resorts for ants using white fabric and cotton ball snow. Apres-ski at five.",
  "Narrate your own struggle with a tangled set of Christmas lights like a Greek tragedy. Fate is cruel.",
  "Author a heartfelt plea to manufacturers about why twist ties should be more intuitive.",
  "Develop rich narrative lives for each of the plants in your neighborhood. The one on the corner is plotting.",
  "Organize a formal farewell for the last bite of a really good meal. It served you faithfully.",
  "Master the exact pause length that makes 'I'm fine' sound just unconvincing enough for follow-up questions.",
  "Evaluate your own breathing technique and rate it for efficiency and drama. You can always improve.",
  "Create a product pitch for a phone that admits when you're just refreshing the same three apps.",
  "Navigate the perilous landscape of old files on your computer. Digital archaeologists would be proud.",
  "Establish a competitive bracket for which of your snacks tastes best at 2 AM. Research is required.",
  "Debate whether doing nothing is still doing something since you're technically existing. Productive laziness.",
  "Assign your loose coins as double agents working between your car and your couch. Trust no cent.",
  "Write the complete oral history of your family's longstanding feud over thermostat settings.",
  "Present a dissertation on the phenomenon of remembering embarrassing moments from years ago for no reason.",
  "Deliver a stirring speech accepting an award for 'Most Time Spent Deciding Where to Eat.'",
  "Construct tiny apartment buildings for your fingers using toilet paper rolls. High-rise living awaits.",
  "Provide commentary on yourself trying to subtly check if your outfit looks okay in reflective surfaces.",
  "Write a formal peace treaty between your desire to stay up late and your need to wake up early.",
  "Create detailed backstories for the abandoned furniture you've passed on the sidewalk. They had families.",
  "Organize a graduation ceremony for your oldest pair of shoes. They've walked many miles with you.",
  "Develop the subtle art of looking busy in a waiting room without actually doing anything productive.",
  "Rate your various sneezes on volume, satisfaction, and the number of 'bless yous' they receive.",
  "Invent a mirror that compliments you but is also honest about that cowlick. Balance is everything.",
  "Lead a nature documentary through your window about the neighbors you've never actually met.",
  "Host a tournament to determine which of your blankets is the coziest. Fierce competition ahead.",
  "Wonder deeply about whether plants are judging your lifestyle choices. They seem judgmental.",
  "Recruit your collection of lids without containers as operatives in a kitchen intelligence network.",
  "Chronicle the great water glass migration that occurs nightly from kitchen to bedroom.",
  "Write a formally peer-reviewed study on why 'just five more minutes' is always a lie.",
  "Accept your Lifetime Achievement Award for looking at your phone when it didn't actually vibrate.",
  "Design a tiny theme park for your earbuds complete with a roller coaster made of their own cord.",
  "Commentate your own attempt to find a comfortable sleeping position. The struggle is Olympic-level.",
  "Compose a passive-aggressive note from your plants about your inconsistent watering schedule.",
  "Develop an extended cinematic universe for the stray buttons in your sewing kit. Drama awaits.",
  "Hold a formal ceremony decommissioning the pen that only works if you hold it at exactly the right angle.",
  "Perfect your reaction for when someone waves and you wave back before realizing they meant someone else.",
  "Write a comprehensive review of your own yawn, rating it for depth, duration, and contagion spread.",
  "Create a device that filters out small talk and only allows conversations about topics you care about.",
  "Explore the ancient civilization that exists behind your washer and dryer. Lost socks thrive there.",
  "Host a competition between your pillows to see which maintains fluffiness longest under pressure.",
  "Philosophize about whether you can actually step in the same river twice. Heraclitus had concerns.",
  "Establish an undercover network using the twist ties from every bread bag you've ever owned.",
  "Write the definitive history of every temporary tattoo you received as a child and where they came from.",
  "Publish your research on the science of why 'the good scissors' are always missing when needed.",
  "Compose your acceptance speech for winning an award for 'Most Convincing Fake Laugh.'",
  "Build tiny obstacle courses for ants using household items. The ant games begin at dawn.",
  "Deliver a nature documentary narration of your struggle to open a stubborn jar. Will human triumph?",
  "Draft a formal proposal to your future self about finally organizing that one catastrophic drawer.",
  "Create the comprehensive mythology of the mysterious dripping sound you sometimes hear at night.",
  "Conduct an official graduation ceremony for yourself for completing another day. Caps and gowns encouraged.",
  "Practice your reaction for when someone pronounces a word differently than you do. Is your whole life a lie?",
  "Write in-depth hotel reviews for various spots your cat has slept. The cardboard box: five stars.",
  "Design a product that translates what people mean when they say 'let's definitely hang out soon.'",
  "Mount an expedition through the rarely-explored second page of Google results. Few have ventured there.",
  "Create a league for racing your various remote controls to see which one's buttons are most responsive.",
  "Debate whether your existence has meaning or whether you're just an intricate series of chemical reactions. Fun!",
  "Assemble a task force of random buttons to infiltrate the sewing basket and report back on conditions.",
  "Document the multi-generational saga of your family's relationship with one specific casserole dish.",
  "Write a peer-reviewed paper on why toast always lands butter-side down. Your hypothesis: cosmic injustice.",
  "Accept your award for excellence in the field of buying books you'll never read but display proudly.",
  "Construct a miniature city for your collection of coins. The penny district is low-income housing.",
  "Provide commentary on your own attempt to parallel park like it's a championship finals moment.",
  "Compose an apology letter to your eyes for all the screens you've subjected them to. They deserve better.",
  "Develop sprawling narratives for each of the photos in your phone's camera roll. Context has been lost forever.",
  "Organize an official retirement ceremony for the umbrella that's been sitting unopened for three years.",
  "Master the art of looking like you're about to say something important but then changing your mind.",
  "Conduct detailed reviews of different corners of your room based on lighting, vibe, and spiderweb potential.",
  "Invent a pillow that remembers exactly how you fluffed it and resets every morning. Revolutionary comfort.",
  "Navigate through the wild jungle that is the back of your closet. Survivors speak of lost hangers.",
  "Challenge your left hand to do everything your right hand usually does. The results will be chaotic.",
  "Contemplate whether a fly flying in a moving car is actually traveling faster than it's ever traveled.",
  "Create a spy ring using the pens from various businesses you've accidentally stolen over the years.",
  "Chronicle the epic tale of how that one weird smell in your garage has evolved over time.",
  "Submit your sleep schedule for formal academic review. Results: concerning but expected.",
  "Write your acceptance speech for being named 'World Champion of Saying You'll Start Tomorrow.'",
  "Design a tiny camping ground for your fingertips using tissues and small boxes. Campfire songs optional.",
  "Provide live breaking news coverage of watching ice melt in your drink. This is happening right now, folks.",
  "Author a formal complaint to whichever evolutionary process decided hiccups were necessary. They're not.",
  "Develop full character arcs for each of the stuffed animals you refuse to throw away. They have feelings.",
  "Host an intervention for the plant that's been barely surviving on your windowsill. It's time to talk.",
  "Perfect the art of the strategic bathroom break during boring situations. Timing is everything.",
  "Evaluate each of your spoons based on their soup-carrying capacity and ice cream scooping potential.",
  "Create a subscription service that sends you motivation when you need it. First month free, disappointment inevitable.",
  "Explore the lost land that exists between your bed and the wall. Ancient artifacts of snack wrappers reside there.",
  "Host a heated debate between your shoes about who has carried you through more difficult times.",
  "Question whether you can actually know anything for certain, or if we're all just guessing. Deep thoughts.",
  "Commission your collection of orphan socks as intelligence operatives. Their partners knew too much.",
  "Write the official history of every password you've ever forgotten and had to reset.",
  "Present your research on why you remember jingles from 20 years ago but not what you ate yesterday.",
  "Compose your speech for receiving an award for 'Most Hours Spent Watching Shows You Weren't Really Into.'",
  "Build a tiny highway system for toy cars using tape on your floor. Traffic laws strictly enforced.",
  "Commentate your own yawning chain reaction like a sporting event. And the yawn spreads to the dog!",
  "Write a heartfelt letter to your past self about the closet organization system you'll eventually abandon.",
  "Create elaborate origin stories for each of the random chargers you have that fit nothing you own.",
  "Conduct formal proceedings to retire your favorite mug that finally cracked. A moment of silence, please.",
  "Cultivate the ability to convey 'I'm listening' while mentally planning dinner. It's an art form.",
  "Rate each of your chairs on comfort, creakiness, and the likelihood you'll actually get up once seated.",
  "Design a device that tells you which pocket your phone is in before you pat all of them down.",
  "Lead an expedition through the contents of your bedside table. Relics of many intentions reside there.",
  "Create a racing league for seeing which of your pens runs out of ink first. May the best pen lose.",
  "Ponder whether deja vu is a glitch in the simulation or just your brain being lazy.",
  "Deploy your collection of expired coupons as spies reporting on deals you'll never actually use.",
  "Record the complete oral tradition of how your family argues about directions on road trips.",
  "Conduct a formal study on the correlation between wanting something and stores being sold out of it.",
  "Prepare your speech for winning 'Most Creative Interpretation of What Clean Room Means.'",
  "Construct tiny rock climbing walls for your fingers using erasers and tape. Summit the desk!",
  "Provide live updates on your attempt to stay awake during something you're supposed to be watching. Losing.",
  "Draft a formal peace accord between you and the corner of furniture you always stub your toe on.",
  "Develop a detailed extended universe for the objects in your medicine cabinet. The expired Tylenol has stories.",
  "Organize an official medal ceremony for the sock that survived the washing machine with no partner.",
  "Perfect the art of subtly checking your phone during a conversation. Ninja-level discretion required.",
  "Write meticulous reviews of each ceiling fan speed, rating them for effectiveness and noise level.",
  "Create a phone case that gently judges you for how many times you've checked social media today.",
  "Explore the archaeological site that is your email's promotional folder. Ancient deals from 2019 await.",
  "Host a tournament to crown which spice in your cabinet is the most underused. Paprika always wins, or loses.",
  "Wonder whether colors look the same to everyone or if we're all just assuming. What is red, really?",
  "Establish a counter-intelligence network among your various storage containers. Information leaks must stop.",
  "Narrate the legendary history of how your family has always done the dishes incorrectly according to you.",
  "Present a dissertation on the physics of why headphone cords tangle instantaneously in pockets.",
  "Accept your award for 'Most Time Spent Staring at Food in the Fridge Without Making a Decision.'",
  "Build tiny ski slopes for your fingernails using tissue boxes. The black diamond runs are treacherous.",
  "Provide commentary on your own internal debate about whether to correct someone's pronunciation. You won't.",
  "Compose an open letter to streaming services about the audacity of asking if you're still watching. Yes. Always.",
  "Create comprehensive backstories for each of the photos hung up in places you visit regularly.",
  "Hold a formal intervention for yourself about your inability to estimate how long tasks take.",
  "Master the expression that says 'I totally understand' when you have no idea what they're talking about.",
  "Conduct thorough reviews of your own handwriting at different times of day. Morning you is illegible.",
  "Design an alarm clock that actually makes you want to wake up. Impossible, but dream big.",
  "Navigate through the uncharted wilderness of old notes in your phone. Mysteries and grocery lists await.",
  "Create a competitive circuit for timing yourself doing mundane tasks and trying to beat your records.",
  "Philosophize about whether mirrors show us as we are or as we think we are. Identity crisis incoming.",
  "Recruit your collection of random receipts as a surveillance network tracking your past spending shame.",
  "Host a formal tribunal to determine which kitchen utensil has betrayed you most often. The vegetable peeler is a prime suspect.",
  "Write a memoir from the perspective of your most neglected houseplant. It's seen your darkest moments.",
  "Create a rating system for the different ways you've accidentally waved at strangers. Rank by awkwardness level.",
  "Conduct an archaeological survey of the mysterious civilization that left artifacts in your dryer's lint trap.",
  "Develop a detailed mythology explaining why batteries in the drawer are always the wrong size.",
  "Host a competitive league for timing how long you can hold your breath while walking past strangers.",
  "Write a strongly-worded formal complaint to your knees about their inconsistent creaking policies.",
  "Create a documentary series about the political tensions between items on different refrigerator shelves.",
  "Design a device that explains why you opened that app and then immediately forgot why.",
  "Lead an expedition into the drawer that holds things you'll 'fix someday.' Fossils await.",
  "Hold a mock United Nations summit between your various snack preferences at different times of day.",
  "Write the tragic origin story of the pen that ran out of ink mid-signature. It died a hero.",
  "Create a formal investigation report on why the fitted sheet always comes undone at 3 AM.",
  "Host a ceremony to officially name the random corner where you always pile stuff temporarily.",
  "Develop a peer-reviewed study on the optimal number of times to hit snooze before it becomes a problem.",
  "Write a Michelin-star review for your most elaborate microwave meal. Two stars for ambition.",
  "Create a competitive sport out of seeing how many items you can carry in one trip. Train daily.",
  "Hold formal peace negotiations between your desire for pizza and your jeans that already feel tight.",
  "Design a tiny monument honoring the brave phone that survived being dropped multiple times.",
  "Lead a safari through the wilderness of your browser's 47 open tabs. Ecosystems thrive there.",
  "Write the epic ballad of the charger cord that still works despite being bent at a 90-degree angle.",
  "Create a formal ceremony for the seasonal changing of the junk from winter coat to spring jacket.",
  "Host a tournament to determine which of your various excuses is most universally applicable.",
  "Develop complete dossiers on each of the mysterious stains on your favorite clothing items.",
  "Write a travel guide for navigating your home at night without turning on lights. Advanced techniques required.",
  "Create a rating system for different types of silence when someone asks who ate the last cookie.",
  "Hold a mock trial for the scissors that are never where you left them. Seek the truth.",
  "Design an elaborate spy mission where you must retrieve a snack without waking anyone up.",
  "Lead a philosophical seminar on whether the five-second rule has any scientific basis. Spoiler: no.",
  "Write the unauthorized biography of your oldest pair of sweatpants. They've seen better days.",
  "Create a formal hierarchy for which apps deserve to be on your home screen. Tough decisions ahead.",
  "Host an intervention for your relationship with that one song you've listened to 400 times.",
  "Develop a mythology explaining the ancient civilization that carved those mysterious scratches on your table.",
  "Write a strongly-worded letter to the concept of 'one more episode' about boundary issues.",
  "Create a competitive event for seeing how many notifications you can ignore in a day. High scores expected.",
  "Hold a formal ceremony acknowledging that you will never use that exercise equipment again.",
  "Design a tiny awards show for the most reliable items in your junk drawer. The tape wins every year.",
  "Lead an expedition to find the source of that one cold spot in your house. It's definitely haunted.",
  "Write a peer-reviewed study on why the bag of chips is always louder when someone's sleeping.",
  "Create a formal investigation into why you always forget what you were going to say mid-sentence.",
  "Host a competitive bracket for ranking your most impressive feats of laziness. The winner takes a nap.",
  "Develop a documentary about the secret lives of socks between the washer and the dryer. Where do they go?",
  "Write the epic saga of the brave rubber band that held things together until it finally snapped.",
  "Create a rating system for the various sounds your body makes when you stand up too fast.",
  "Hold a mock academic conference on the optimal ratio of toppings to pizza base. Contentious debates expected.",
  "Design a tiny memorial for all the hair ties that have been lost to the void of your home.",
  "Lead a philosophical inquiry into whether you're lying in bed or lying to yourself about getting up.",
  "Write a formal charter establishing your right to eat questionable leftovers without judgment.",
  "Create a competitive league for speed-scrolling through streaming services without choosing anything.",
  "Host an awards ceremony for the most dramatic sighs you've produced this week. Categories include 'existential' and 'mildly inconvenienced.'",
  "Develop a detailed backstory for the mystery key on your keychain that opens absolutely nothing you know of.",
  "Write a strongly-worded petition to the universe about the unfairness of having to eat multiple times daily.",
  "Create a formal investigation into why the best shower thoughts only occur when you can't write them down.",
  "Hold a summit between your productive morning self and your 'just five more minutes' self. Seek compromise.",
  "Design a tiny spa day for your most overworked fingers. The typing ones need a break.",
  "Lead a nature documentary about the migratory patterns of items between your desk and your floor.",
  "Write the official constitution of the independent nation of your bed. All are welcome, none may leave.",
  "Create a rating system for the emotional impact of different types of weather on your desire to do anything.",
  "Host a formal debate on whether standing in front of the open fridge actually helps you decide what to eat.",
  "Develop a comprehensive encyclopedia of all the sounds your home makes that you've chosen to ignore.",
  "Compose an acceptance speech for winning the prestigious award of 'Person Most Likely to Start a Project and Never Finish It.'"
];
