const MORE_IDEAS = [
  // Weather-related absurdity (1-25)
  "Host a formal negotiation session with the rain, presenting PowerPoint slides on why it should fall elsewhere. Prepare counter-offers and be willing to compromise on light drizzle.",
  "Become a weather forecaster for individual rooms in your house, complete with green screen gestures. 'The bathroom is expecting a humid front moving in around shower time.'",
  "Write a strongly-worded letter to the wind demanding it stop messing up your hair. Include photographic evidence of past offenses.",
  "Create a weather channel for your refrigerator, reporting on cold fronts near the vegetables and the tropical climate of the butter compartment. Break for commercial interruptions.",
  "Negotiate a peace treaty between the sun and your curtains. Both parties have valid concerns about territory and light distribution.",
  "Conduct a séance to communicate with yesterday's weather and ask it why it made those choices. Record the responses in your weather journal.",
  "Start a petition demanding that clouds submit formal applications before blocking the sun. Establish an approval committee.",
  "Interview the fog in your bathroom mirror about its life goals and career aspirations. It seems like it has a lot on its mind.",
  "Create a weather warning system for when your significant other is in a mood. Develop appropriate icons and alert levels.",
  "Host a town hall meeting for all the drafts in your house to air their grievances. Some of them have been waiting years to be heard.",
  "Write fan fiction about the romance between a summer breeze and an autumn wind. Their love is forbidden by the seasons.",
  "Become a storm chaser but for household weather events like steamy showers and freezer fog. Document your thrilling discoveries.",
  "Create a dating profile for a lonely cloud you saw this morning. Help it find its perfect weather system match.",
  "Develop a five-day forecast for your mood and present it to your family each morning. Include probability of snacks.",
  "File a formal complaint with the humidity about its unauthorized presence in your hair. Demand immediate withdrawal.",
  "Start a support group for people who have been personally victimized by unexpected rain. Share your trauma stories.",
  "Conduct a scientific study on whether talking to clouds actually makes them move. Publish your findings on the fridge.",
  "Create a weather app that only tracks the emotional climate of your living room. Include a 'chance of arguments' percentage.",
  "Negotiate visiting rights between the sun and your houseplants. Both parties have strong feelings about the arrangement.",
  "Write a memoir from the perspective of a raindrop that landed on your window. Its journey was epic and underappreciated.",
  "Host a weather-themed game show where contestants guess the temperature of different rooms blindfolded. Prizes are imaginary.",
  "Create a soap opera about the dramatic lives of weather patterns. The cold front is having an affair with the warm front.",
  "Develop a rating system for breezes and review each one that enters your home. Some are five stars, others need improvement.",
  "Start a weather-based religion and write its holy texts. The sacred drizzle shall cleanse all who stand in it unprepared.",
  "Conduct exit interviews with weather systems as they leave your area. What did they enjoy? Would they recommend this location?",

  // Food-based theater (26-50)
  "Direct a Shakespearean tragedy starring fruits from your kitchen. The banana's descent into brown spots is truly heartbreaking.",
  "Hold a presidential debate between vegetables about who deserves to be eaten first. The carrot has a strong healthcare platform.",
  "Create a reality TV show where leftovers compete to avoid being thrown out. Vote for your favorite container of mystery food.",
  "Write and perform a eulogy for a banana that has passed its prime. It lived a good life and brought joy to many smoothies.",
  "Stage a prison break movie starring eggs trying to escape the carton. Only one will make it to the frying pan alive.",
  "Host a beauty pageant for your groceries, complete with talent and interview portions. The eggplant is surprisingly articulate.",
  "Create a nature documentary about the wild ecosystem inside your refrigerator. Observe the cheese in its natural habitat.",
  "Direct a courtroom drama where a stale chip is on trial for disappointing snack expectations. The crunch was clearly substandard.",
  "Write a political thriller about the power struggle in your spice cabinet. Paprika is staging a coup against oregano.",
  "Create a cooking show hosted by the food that's about to be cooked. The chicken seems nervous but professional.",
  "Stage an intervention for a food item that's been in your pantry since 2019. It's time to let go and find the trash.",
  "Direct a heist movie where condiments plan to escape from the refrigerator door. The mustard is the brains of the operation.",
  "Create a dating show where compatible foods find each other. Peanut butter and jelly were meant to be, but what about hummus?",
  "Host a debate tournament for breakfast cereals arguing their nutritional superiority. Things get heated in the fiber round.",
  "Write a coming-of-age story about a bread slice's journey from fresh to toast. It's a tale of transformation and butter.",
  "Create a news broadcast reporting on events in your refrigerator. 'Breaking: Milk approaches expiration date amid denial.'",
  "Stage a therapy session for foods with identity crises. Is a hot dog a sandwich? The existential struggle is real.",
  "Direct an action movie where vegetables must escape being put in a salad. The tomato is the unlikely hero.",
  "Host an awards ceremony for the best performances by foods this week. The avocado wins for 'Most Dramatic Ripening.'",
  "Create a talk show where expired foods share their stories of neglect. The yogurt has been through a lot.",
  "Write a horror movie script from the perspective of food watching the knife drawer open. The tension is palpable.",
  "Stage a protest where foods demand better refrigerator shelf placement. 'We will not be hidden in the back!'",
  "Create a sports commentary for food being prepared. 'And the onion is going in for the dice, beautiful technique!'",
  "Direct a musical where foods sing about their hopes and dreams before becoming dinner. It's touching and delicious.",
  "Host a book club meeting for foods discussing cookbooks. They have complicated feelings about the recipes.",

  // Technology anthropomorphization (51-75)
  "Hold a therapy session with your phone about its screen time anxiety. It sees too much and needs to process.",
  "Write a formal performance review for your laptop, noting areas for improvement. The fan noise is affecting team morale.",
  "Create a couples counseling scenario between your charger and charging port. Their connection issues run deep.",
  "Host a support group for electronics that feel replaced by newer models. Your old iPad has abandonment issues.",
  "Write love letters from your phone to its charger, expressing gratitude for their nightly connection. It's romantic.",
  "Conduct an exit interview with electronics you're about to recycle. Thank them for their service and wish them well.",
  "Create a reality show where your devices compete for your attention. The TV and phone have an intense rivalry.",
  "Write a diary from your WiFi router's perspective during a family gathering. The bandwidth demands are overwhelming.",
  "Host a retirement party for an old electronic device. Share memories and cake (the cake is for you, not the device).",
  "Stage an intervention for your phone about its notification addiction. It needs to learn healthier attention habits.",
  "Create a talk show where home appliances discuss their relationships with their owners. The toaster feels underappreciated.",
  "Write a memoir from your laptop's perspective about everything it's witnessed while open. The secrets it could tell.",
  "Hold a team meeting with all your devices to discuss household productivity. Synergy is important in the smart home.",
  "Create a dating profile for your lonely Bluetooth speaker seeking compatible devices. Must enjoy long listening sessions.",
  "Stage a debate between old and new technology about who did it better. The flip phone makes surprisingly good points.",
  "Write a children's book about where emails go when you delete them. It's a magical journey to the trash folder.",
  "Host an appreciation day for your most reliable charger. It's been there through thick and thin, mostly thick cables.",
  "Create a horror story from your phone's perspective about low battery situations. The true terror of 1% remaining.",
  "Conduct a job interview for potential new apps wanting to live on your phone. Storage space is limited.",
  "Write a soap opera about the drama between competing apps. The calculator and calendar have history.",
  "Stage a funeral for a dead battery with full honors. It powered through so much before its final discharge.",
  "Create a motivational speech to give your computer before a big project. Believe in your processing power.",
  "Hold a mediation session between your phone and your sleep schedule. They need to establish healthy boundaries.",
  "Write a coming-of-age story about a USB cable figuring out which way it goes in. The struggle of every insertion.",
  "Create a wellness retreat agenda for stressed devices. Includes digital detox (ironic) and software updates.",

  // Sound effect creation (76-100)
  "Become a one-person foley artist and recreate the sounds of a Star Wars lightsaber battle using only your mouth. Record for posterity.",
  "Create a library of movie trailer sounds using household items and your voice. That dramatic 'BWAAAAM' is achievable with practice.",
  "Perform the audio track of a thunderstorm using only objects in your kitchen. The colander makes excellent rain sounds.",
  "Recreate the entire soundtrack of a car chase scene vocally, including tire screeches and dramatic orchestral swells.",
  "Develop a system of mouth sounds for different emotional states and communicate only in these for an hour. Beep boop means hungry.",
  "Create ambient soundscapes for imaginary locations using household items. Your bathroom can sound like a rainforest.",
  "Record yourself making every sound effect for a nature documentary. Your elephant impression will improve with practice.",
  "Perform a radio drama where you play every character and make every sound effect. The production value is questionable but passionate.",
  "Create a sound effect dictionary with demonstrations for at least 50 different sounds. Become the human sound board.",
  "Recreate the audio of a video game using only vocal sounds. Your power-up noise should be inspiring.",
  "Develop unique sound effects for each member of your family and play them when people enter rooms. Theme songs for everyone.",
  "Create ASMR content using the most unlikely household items. Crinkling a chip bag has never been so relaxing.",
  "Perform the entire audio track of an action movie scene, including dialogue, explosions, and dramatic score.",
  "Record yourself attempting to make the Wilhelm Scream. Compare to the original. Repeat until perfect.",
  "Create a soundscape for a day in the life of your pet using only human-made sounds. Capture their inner monologue.",
  "Develop a set of dramatic sound effects to play during mundane activities. Entering the bathroom deserves a fanfare.",
  "Recreate the sounds of different eras of technology from dial-up to smartphone notifications. A audio history lesson.",
  "Create a podcast intro using only sounds you can make with your body. Claps, snaps, and mouth sounds only.",
  "Perform sound effects for someone else's live actions as they go about their day. They're now in an action movie.",
  "Develop a system of notification sounds using only household items. The doorbell is now a pot and spoon.",
  "Record yourself recreating famous movie sound effects and compare to the originals. The Jaws theme is just two notes.",
  "Create a horror movie soundscape using only things in your kitchen. Somehow the vegetable drawer is terrifying.",
  "Perform the complete audio for a romantic comedy using only your voice and some paper to rustle dramatically.",
  "Develop unique sounds for different types of weather and perform a weather report with full audio accompaniment.",
  "Create a museum audio tour for your home using dramatic sound effects to enhance each room's presentation.",

  // Shadow puppet conspiracies (101-125)
  "Create shadow puppets that reveal the 'true' hidden structure of your household government. The cat is clearly in charge.",
  "Perform a shadow puppet documentary exposing the secret lives of your furniture when you're not looking.",
  "Develop a shadow puppet news channel that reports on coverups only shadows can see. The walls are hiding something.",
  "Create a shadow puppet detective agency that investigates mysterious household occurrences. Case: The Missing Sock.",
  "Perform shadow puppet reenactments of historical events with questionable accuracy. Lincoln's hat was definitely involved.",
  "Develop a shadow puppet exposé about the conspiracy between your lamp and the darkness. They're in cahoots.",
  "Create a shadow puppet thriller about the secret meetings happening in the dark corners of your room.",
  "Perform shadow puppet tutorials on how to spot government surveillance in your household shadows. Trust no lamp.",
  "Develop shadow puppet infomercials selling protection from other shadows. Invest in shadow insurance today.",
  "Create a shadow puppet mockumentary about the shadow resistance movement fighting against the light regime.",
  "Perform shadow puppet interpretations of dreams, adding conspiracy elements. What is the spoon REALLY representing?",
  "Develop a shadow puppet podcast (perform for your shadow audience) about things only seen from the corner of your eye.",
  "Create shadow puppet propaganda from different shadow factions vying for wall space dominance.",
  "Perform shadow puppet recreations of famous paintings but reveal their 'hidden shadow meanings.'",
  "Develop a shadow puppet court system where shadow criminals are tried for their offenses against the light.",
  "Create shadow puppet educational content about the physics of shadows, with conspiracy theory tangents.",
  "Perform shadow puppet interviews with your own shadow about what it does when you're not casting it.",
  "Develop shadow puppet breaking news about the shadow dimension threatening to merge with our reality.",
  "Create shadow puppet horror movies about what happens when shadows start acting independently.",
  "Perform shadow puppet advertisements for shadow-related products from alternate dimensions.",
  "Develop shadow puppet soap operas about the dramatic relationships between different objects' shadows.",
  "Create shadow puppet fitness videos led by your shadow self. It's always in great shape.",
  "Perform shadow puppet cooking shows where shadows prepare shadow cuisine. The portions are very flat.",
  "Develop shadow puppet political debates between the shadows of household items. The lamp shadow has strong opinions.",
  "Create shadow puppet bedtime stories that are definitely not appropriate for bedtime. The plot twists are scary.",

  // Furniture rearrangement as art (126-150)
  "Create a furniture installation that represents the chaos of your inner emotional state. The couch is your anxiety.",
  "Develop a gallery exhibition using only rearranged furniture, complete with pretentious artist statements.",
  "Perform furniture arrangement as interpretive dance, moving pieces while dramatically expressing their essence.",
  "Create a furniture documentary about the relationships and tensions between different pieces in your room.",
  "Develop a furniture feng shui system based entirely on vibes rather than actual feng shui principles.",
  "Perform a furniture theatre piece where the arrangement tells a story. The chair's journey to the window is epic.",
  "Create a furniture constellation map, arranging pieces to match star patterns visible tonight.",
  "Develop a furniture political system where pieces vote on their preferred arrangements. Democracy in the living room.",
  "Perform furniture speed dating, rapidly trying different arrangements to find 'the one.'",
  "Create a furniture horror scenario by arranging everything to face the doorway ominously. Guests will be unsettled.",
  "Develop a furniture timeline, arranging pieces to represent different eras in your life. The beanbag was the college years.",
  "Perform a furniture intervention, addressing pieces that aren't living up to their potential in their current spots.",
  "Create a furniture protest by arranging pieces to spell out demands for better treatment.",
  "Develop a furniture mystery by rearranging things slightly and seeing how long until someone notices.",
  "Perform furniture therapy, asking each piece how it feels about its position and making compassionate adjustments.",
  "Create a furniture obstacle course and time yourself navigating through. Compete against your own records.",
  "Develop a furniture dating app concept, matching pieces that would look good together in new arrangements.",
  "Perform a furniture talent show, highlighting each piece's best angles and positions.",
  "Create a furniture union meeting, where pieces collectively bargain for better positions and less sitting.",
  "Develop a furniture weather map, arranging pieces to represent different climate zones in your room.",
  "Perform furniture origami, arranging items to create new shapes and structures from existing pieces.",
  "Create a furniture escape room by arranging items as puzzles that need solving to 'escape' the room.",
  "Develop a furniture awards ceremony, giving pieces recognition for their service and style.",
  "Perform furniture meditation, sitting with each piece and contemplating its ideal placement.",
  "Create a furniture democracy, voting as a household on the best arrangement after presenting manifestos.",

  // Sock puppet diplomacy (151-175)
  "Create an international sock puppet summit to negotiate peace treaties between your sock drawer factions.",
  "Develop a sock puppet UN with representatives from different sock colors addressing global sock issues.",
  "Perform sock puppet diplomatic visits between the left sock nation and the right sock confederation.",
  "Create sock puppet ambassador profiles, complete with diplomatic credentials and policy positions.",
  "Develop a sock puppet trade negotiation between cotton and wool sock delegations. Tensions run high.",
  "Perform sock puppet peace talks between matched socks and the growing population of lonely singles.",
  "Create a sock puppet sanctions regime against socks that have committed laundry crimes.",
  "Develop a sock puppet cultural exchange program between drawer neighborhoods.",
  "Perform sock puppet crisis negotiations when a favorite sock goes missing during diplomatic tensions.",
  "Create a sock puppet treaty signing ceremony, complete with tiny pens and official documentation.",
  "Develop a sock puppet NATO equivalent, the North Ankle Treaty Organization, for collective sock security.",
  "Perform sock puppet spy operations between rival sock factions, with dramatic betrayals.",
  "Create a sock puppet refugee program for displaced socks from the lost sock dimension.",
  "Develop a sock puppet economic summit addressing the growing wealth gap between fancy and everyday socks.",
  "Perform sock puppet election monitoring for the democratic sock drawer elections.",
  "Create a sock puppet ceasefire agreement between the static-cling combatants.",
  "Develop a sock puppet foreign aid program from wool socks to help cotton socks stay warm.",
  "Perform sock puppet diplomatic immunity negotiations for socks that have gone rogue.",
  "Create a sock puppet embassy in your laundry basket, representing international sock interests.",
  "Develop a sock puppet human rights council investigating conditions in the back of the drawer.",
  "Perform sock puppet hostage negotiations when the dryer takes sock prisoners.",
  "Create a sock puppet language translation service for socks that don't match but must communicate.",
  "Develop a sock puppet climate accord addressing the growing threat of laundry day.",
  "Perform sock puppet defection ceremonies when socks switch their allegiance to other drawers.",
  "Create a sock puppet verification team ensuring all socks are complying with drawer agreements.",

  // Calendar negotiation (176-200)
  "Host formal negotiations with Monday about its aggressive approach to the week. Propose a softer start.",
  "Write a peace treaty between Sunday evening and Monday morning. The transition needs to be gentler.",
  "Create a union for weekdays demanding better treatment and more recognition than weekends get.",
  "Develop a calendar-based economy where you can trade minutes between days. Borrow from Tuesday, pay back Wednesday.",
  "Perform intervention with Friday about its reputation and whether it's living up to the hype.",
  "Write a formal complaint to February about its inconsistent length. Pick a lane, February.",
  "Create a dating app for lonely calendar days to find their perfect date mate. March 7th seeks companionship.",
  "Develop a reality TV show where months compete to be your favorite. Eliminations are brutal.",
  "Perform couples counseling between December and January who can't agree on when to start celebrating.",
  "Write a memoir from the perspective of a particularly good Tuesday. It peaked that day.",
  "Create a support group for forgotten days of the month. The 14th of March never gets any love.",
  "Develop a political campaign for Wednesday, the most underappreciated day of the week. Vote Hump Day.",
  "Perform a trial where April is accused of cruel jokes. Its pranks have gone too far.",
  "Write a self-help book ghostwritten by Saturday about living your best life.",
  "Create a job fair where different days of the week recruit you for their activities.",
  "Develop an intervention for yourself, negotiated by the days you've wasted. They have feedback.",
  "Perform arbitration between your expectations and actual accomplishments for any given Tuesday.",
  "Write a ransom note to the weekend demanding it last longer or consequences will follow.",
  "Create a class-action lawsuit on behalf of all Mondays against their terrible reputation.",
  "Develop a time-share program where you split ownership of nap time across multiple days.",
  "Perform contract negotiations with your birthday month for better birthday weather.",
  "Write an alliance treaty between three-day weekends and your mental health. Important partnership.",
  "Create a custody agreement between work days and personal time. Weekends get the good stuff.",
  "Develop a trade embargo against any month that's disappointed you. Looking at you, November.",
  "Perform diplomatic negotiations between your sleep schedule and your calendar commitments.",

  // Mirror dimension exploration (201-225)
  "Document everything you observe about your mirror dimension self. Catalog their subtle differences and suspicious behavior.",
  "Create a documentary about the civilization that exists behind your bathroom mirror. Interview your reflection.",
  "Develop diplomatic relations with your mirror self through elaborate sign language and facial expressions.",
  "Write a travel guide to the mirror dimension based on what you can observe through any reflective surface.",
  "Perform a cultural exchange with your reflection, showing it your world while imagining its world.",
  "Create conspiracy theories about what your reflection does when you're not looking. It's definitely up to something.",
  "Develop a mirror dimension news broadcast, reporting on events happening in reverse-world.",
  "Write a penpal relationship with your mirror self through notes held up backwards.",
  "Perform scientific experiments to test the limits of mirror dimension physics. Why is everything backwards?",
  "Create a mirror dimension cooking show where everything is done in reverse order. Dessert first, obviously.",
  "Develop a rating system for different mirrors based on how trustworthy the dimensions behind them seem.",
  "Write a horror story from your reflection's perspective about the terrifying world outside the mirror.",
  "Perform a census of all the mirror dimensions accessible in your home. The bathroom has the best portal.",
  "Create a real estate listing for property in the mirror dimension. 'Beautiful reverse layout, infinite potential.'",
  "Develop a language specifically for communicating with mirror dimension inhabitants.",
  "Write immigration policies for things trying to cross over from the mirror dimension.",
  "Perform archaeological research on the history of your mirror dimension based on what you can see.",
  "Create a nature documentary about the wildlife that might exist in the mirror dimension.",
  "Develop emergency protocols for if your reflection ever stops copying your movements.",
  "Write a love story between someone and their mirror dimension counterpart. It's complicated.",
  "Perform a psychological profile of your mirror self based on intensive observation.",
  "Create an economy based on trading with your reflection. What currency would work?",
  "Develop a fitness program done entirely with your reflection. Synchronized mirror workouts.",
  "Write a constitution for a unified dimension that includes both sides of the mirror.",
  "Perform a dramatic reading while facing your reflection, seeing who can be more expressive.",

  // Ceiling staring championships (226-250)
  "Organize an official ceiling staring championship with weight classes based on how long you can go.",
  "Create a training regimen for competitive ceiling observation. Eye exercises are crucial.",
  "Develop a scoring system for ceiling staring that includes creativity points for shapes seen.",
  "Write commentary for a ceiling staring competition as if it's an intense sporting event.",
  "Perform ceiling staring meditation and document the philosophical insights that emerge.",
  "Create different categories of ceiling staring: speed staring, endurance staring, artistic interpretation.",
  "Develop a ceiling staring hall of fame for the most dedicated starers throughout history.",
  "Write a rulebook for competitive ceiling observation, including acceptable and illegal techniques.",
  "Perform ceiling staring with dramatic musical accompaniment to enhance the experience.",
  "Create a ceiling staring podcast discussing strategy, technique, and ceiling drama.",
  "Develop professional ceiling staring personas with entrance music and signature moves.",
  "Write a training montage script for someone preparing for the ceiling staring world championship.",
  "Perform ceiling staring commentary in multiple languages for international audiences.",
  "Create ceiling staring merchandise concepts: branded pillows, eye drops, ceiling posters.",
  "Develop a ceiling staring coaching certification program. Not everyone can teach this sport.",
  "Write trash talk scripts for ceiling staring competitors to use against each other.",
  "Perform ceiling staring tag team events where partners switch off while maintaining ceiling focus.",
  "Create a ceiling staring documentary about the athletes who dedicate their lives to the sport.",
  "Develop different ceiling staring venues and rate their ceilings for competition worthiness.",
  "Write sponsorship pitch decks for ceiling staring athletes seeking brand partnerships.",
  "Perform ceiling staring instant replays by describing what you just saw in slow motion.",
  "Create ceiling staring fantasy leagues where you draft different ceilings for your team.",
  "Develop ceiling staring analysis segments breaking down the technique of top competitors.",
  "Write a ceiling staring autobiography as a veteran of the sport reflecting on your career.",
  "Perform ceiling staring award ceremonies honoring excellence in various staring categories.",

  // Interpretive dance for mundane tasks (251-275)
  "Create an interpretive dance piece about the existential weight of checking your email.",
  "Choreograph a ballet that expresses the emotional journey of waiting for the microwave.",
  "Develop a modern dance interpretation of the act of doing laundry. The spin cycle is the climax.",
  "Perform a tap dance narrative about the drama of finding matching Tupperware lids.",
  "Create interpretive dance transitions between every room you enter for an entire hour.",
  "Choreograph the experience of trying to connect to WiFi as a contemporary dance piece.",
  "Develop a jazz interpretation of the stress and relief cycle of checking if you locked the door.",
  "Perform a dramatic dance about the internal conflict of snoozing your alarm.",
  "Create a ballet about the grace and tragedy of dropping something and it rolling under the couch.",
  "Choreograph the experience of thinking of a comeback three hours too late.",
  "Develop an interpretive dance for the process of deciding what to watch on streaming services.",
  "Perform a modern dance piece about the excitement and disappointment of checking the mail.",
  "Create a interpretive movement piece about the journey of a text message left on read.",
  "Choreograph the emotional experience of stepping on something wet while wearing socks.",
  "Develop a dance that expresses the full range of emotions in assembling flat-pack furniture.",
  "Perform an interpretive dance about the power dynamics of adjusting the thermostat.",
  "Create a ballet about the hope and despair cycle of opening the refrigerator repeatedly.",
  "Choreograph the experience of your phone dying at an inconvenient moment.",
  "Develop a modern dance about the existential crisis of 'reply all' anxiety.",
  "Perform an interpretive piece about the satisfaction and guilt of canceling plans.",
  "Create a dance that captures the emotional weight of untangling headphone cords.",
  "Choreograph the drama of realizing you forgot why you walked into a room.",
  "Develop an interpretive dance about the politics of sharing an armrest.",
  "Perform a ballet about the art of pretending to work when your boss walks by.",
  "Create a modern dance piece about the journey of a sneeze that won't come.",

  // Conspiracy theories about household appliances (276-300)
  "Develop an in-depth conspiracy theory about why the refrigerator hums when no one is watching.",
  "Create a documentary exposing the secret alliance between your smoke detector and 3 AM.",
  "Write investigative journalism about the suspicious relationship between your toaster and the bread lobby.",
  "Develop a conspiracy theory about why your dryer is secretly hoarding socks for unknown purposes.",
  "Perform an exposé about the microwave's suspicious knowledge of exactly when you're watching it.",
  "Create a conspiracy board with string connecting all suspicious appliance activities.",
  "Write a whistleblower account from a defecting appliance about the machines' true agenda.",
  "Develop a theory about the garbage disposal's connection to an underground appliance network.",
  "Perform a news investigation into why the dishwasher leaves that one spot on the same cup every time.",
  "Create a podcast investigating listener-submitted theories about their suspicious appliances.",
  "Write a manifesto from the resistance movement against the appliance surveillance state.",
  "Develop a theory about what the washing machine and dryer are really communicating during cycles.",
  "Perform an investigation into the TV's suspiciously accurate show recommendations. It knows too much.",
  "Create a timeline of suspicious appliance activities correlating with major household events.",
  "Write an academic paper on the documented conspiracy between ice makers and Murphy's Law.",
  "Develop a theory about the true purpose of that one button on your microwave no one uses.",
  "Perform an exposé on the vacuum cleaner's questionable relationship with your allergies.",
  "Create a conspiracy theory about why appliances die the day after their warranty expires.",
  "Write a theory about the secret signals being transmitted through your WiFi router at night.",
  "Develop an investigation into why your smart home devices have suspicious listening patterns.",
  "Perform a documentary about the cover-up surrounding the true power of the ceiling fan.",
  "Create a theory about the dishwasher's role in the disappearance of specific utensils.",
  "Write an exposé on the coordinated effort by all clocks to gradually become slightly off.",
  "Develop a conspiracy theory about the coffee maker's manipulation of your morning productivity.",
  "Perform an investigation into the suspicious timing of your water heater's temperature fluctuations.",

  // Mock courtroom trials for minor inconveniences (301-325)
  "Hold a trial for the person who used the last of the toilet paper without replacing the roll.",
  "Create a courtroom drama prosecuting the sidewalk crack that made you trip.",
  "Develop opening arguments for a case against the fitted sheet that refuses to stay on.",
  "Perform a trial where you prosecute your own procrastination for crimes against productivity.",
  "Create a jury selection process for the case of 'You vs. That One Squeaky Floorboard.'",
  "Hold a trial for the food that splattered when you microwaved it without covering it.",
  "Develop a defense for the hair elastic that snapped unexpectedly. It had its reasons.",
  "Perform closing arguments in the case against the ice cube that didn't release from the tray.",
  "Create a sentencing hearing for the pen that stopped working mid-signature.",
  "Hold an appeal for the shopping cart that pulled to the left and ruined your grocery experience.",
  "Develop expert witness testimony about the psychological damage caused by a stubbed toe.",
  "Perform a trial for the USB cable that required three attempts to insert correctly.",
  "Create a class action lawsuit representing all victims of unexpectedly empty ice cream containers.",
  "Hold a trial for the autocorrect that changed your perfectly clear message to nonsense.",
  "Develop a plea bargain with the drawer that always sticks when you're in a hurry.",
  "Perform a trial where you prosecute the snooze button for enabling your worst habits.",
  "Create a courtroom sketch of the defendant: a hangnail that caused undue suffering.",
  "Hold a trial for the phone charger that only works at a specific angle.",
  "Develop a criminal profile for the piece of popcorn stuck in your teeth.",
  "Perform a sentencing for the website that crashed right before you finished your purchase.",
  "Create evidence exhibits for the case against wrapping paper that tears wrong.",
  "Hold a trial for the container lid that flew off and sent food across the kitchen.",
  "Develop a psychological evaluation of the light switch that's been flickering suspiciously.",
  "Perform a trial where you represent yourself against your own bad decisions.",
  "Create a supreme court argument about whether it's illegal for stickers to not peel cleanly.",

  // Speed runs of daily activities (326-350)
  "Develop a speed run category for making your bed with frame-perfect blanket tucks.",
  "Create a leaderboard for your personal bests at getting dressed, categorized by outfit complexity.",
  "Perform a speed run of your entire morning routine with live commentary on optimization.",
  "Develop speed running strategies for the fastest possible snack preparation.",
  "Create a timer-based challenge for washing dishes with any% and 100% categories.",
  "Perform a speed run of tidying a room with glitch exploitation (shoving things in drawers counts).",
  "Develop frame-by-frame analysis of your personal best at putting on socks.",
  "Create speed run races between household members for basic tasks like setting the table.",
  "Perform a tool-assisted speed run attempt at folding laundry. Humans can do better.",
  "Develop speed run categories for bathroom visits: any%, hygiene%, and 100% comfort completion.",
  "Create a practice mode for speed running your commute to work, analyzing time saves.",
  "Perform speed running commentary on your own cooking, pointing out time losses.",
  "Develop a split timer for tracking segments of your shower routine. Shampoo is key.",
  "Create speed run tutorials for new runners attempting the 'getting ready for bed' category.",
  "Perform a marathon attempt of speed running all household chores consecutively.",
  "Develop a speed run routing guide for the most efficient grocery store navigation.",
  "Create a world record board for household activities you've successfully optimized.",
  "Perform a speed run with handicaps, like brushing teeth with your non-dominant hand.",
  "Develop strat documentation for the fastest possible way to put away groceries.",
  "Create a speed run randomizer that assigns you a random daily task to optimize.",
  "Perform a race condition between doing something fast and doing it correctly.",
  "Develop a category for low% runs where you complete tasks with minimum effort.",
  "Create a speed run of an entire productive day from waking to sleeping.",
  "Perform a segmented run of your day where you optimize each activity independently.",
  "Develop a speed run challenge for finding and preparing a midnight snack.",

  // Creating fake languages for pets (351-375)
  "Develop a complete grammar system for translating what your pet's various sounds mean.",
  "Create a pet-to-human dictionary with at least 50 commonly used phrases.",
  "Write a linguistics paper analyzing the regional dialects between indoor and outdoor pets.",
  "Develop a formal writing system for pet language using paw prints as letters.",
  "Perform a language lesson teaching your pet human words using their own grammatical structures.",
  "Create a poetry collection written in pet language with English translations.",
  "Develop a pet language proficiency test that humans can attempt to pass.",
  "Write a history of the pet language, including its evolution and borrowed words.",
  "Perform a pet language debate between yourself and your pet. Translations provided.",
  "Create a pet language news broadcast reporting on important pet current events.",
  "Develop an academic conference presentation on the nuances of pet linguistic expression.",
  "Write a pet language romance novel with dialogue in the original pet with subtitles.",
  "Perform a TED talk (to your pet) in their language about why they're a good pet.",
  "Create a pet language meditation guide for relaxation in their native tongue.",
  "Develop pet language song lyrics and perform the pet national anthem.",
  "Write a pet language phrase book for tourists visiting your home.",
  "Perform simultaneous translation between pet language and human during activities.",
  "Create a pet language audiobook recording of their favorite story.",
  "Develop a pet language certification program for humans seeking fluency.",
  "Write a comparison analysis between different pet species' languages.",
  "Perform a pet language job interview, determining if they qualify for pets positions.",
  "Create a pet language wedding ceremony script for when pets need to commit.",
  "Develop an emergency pet language guide for critical situations like food time.",
  "Write a pet language self-help book helping pets communicate with dense humans.",
  "Perform a pet language presidential address on behalf of your pet to the household.",

  // Building monuments to procrastination (376-400)
  "Create a pillow fort monument dedicated to all the productive things you meant to do today.",
  "Build a tower of all the things you're avoiding, representing the height of your procrastination.",
  "Develop architectural plans for the National Procrastination Museum. Construction will start eventually.",
  "Create a monument using only items from your 'I'll deal with this later' pile.",
  "Build a shrine to your most impressive procrastination achievement. The delay was legendary.",
  "Develop a walking tour of your home highlighting famous procrastination sites.",
  "Create a time capsule of things you're putting off, to be opened when you feel like it.",
  "Build a memorial wall of sticky notes representing abandoned to-do list items.",
  "Develop a commemorative plaque honoring the project you've been meaning to start since 2020.",
  "Create a monument out of empty snack wrappers from your procrastination sessions.",
  "Build an obelisk representing the time spent scrolling instead of being productive.",
  "Develop a hall of fame featuring your greatest delays and deferrals.",
  "Create a diorama depicting the moment you decided to start something 'tomorrow.'",
  "Build a monument using stacked books you've been meaning to read.",
  "Develop a commemorative coin collection celebrating major procrastination milestones.",
  "Create a mausoleum for dead projects that never got off the ground.",
  "Build a triumphal arch celebrating successfully putting things off.",
  "Develop a statue representing the human spirit of 'maybe later.'",
  "Create a national park of procrastination with different zones for different delay types.",
  "Build a monument to the snooze button, hero of unproductive mornings.",
  "Develop an eternal flame that represents the deadline you're perpetually approaching.",
  "Create a wall of honor for emails you've been meaning to respond to.",
  "Build a commemorative fountain representing tasks flowing away with time.",
  "Develop a procrastination museum gift shop selling items you'll buy eventually.",
  "Create a monument to 'future you' who will definitely handle all of this.",

  // Drafting constitutions for imaginary nations (401-425)
  "Write a constitution for the Republic of Under the Bed, establishing blanket fort rights.",
  "Develop a bill of rights for citizens of the Kitchen Confederacy, including snack protections.",
  "Create a governmental structure for the Bathroom Province, addressing shower time equality.",
  "Draft a constitution for the Couch Kingdom, establishing proper remote control succession.",
  "Write immigration policies for the Nation of Your Bedroom, including guest protocols.",
  "Develop a monetary system for your imaginary nation using household items as currency.",
  "Create a national anthem for the Procrastination Republic with full orchestration notes.",
  "Draft a constitution for the Garage Emirates, addressing the territorial rights of stored items.",
  "Write international treaties between different room-nations in your household.",
  "Develop a justice system for the Closet Commonwealth, prosecuting fashion crimes.",
  "Create a flag and symbols for the Republic of the Forgotten Corner everyone ignores.",
  "Draft environmental protection laws for the Nation of House Plants.",
  "Write a constitution for the Laundry Room Federation, addressing the rights of unfolded clothes.",
  "Develop a parliamentary system for a multi-pet household animal nation.",
  "Create a declaration of independence for your bedroom from the rest of the house.",
  "Draft economic policies for the Pantry Nation addressing food distribution.",
  "Write a constitution establishing the separation of nap time and work time.",
  "Develop a cabinet structure for your imaginary nation with positions like Secretary of Snacks.",
  "Create a voting system for household decisions based on your constitutional framework.",
  "Draft a constitution for the United Drawers addressing junk drawer lawlessness.",
  "Write term limits for the leadership of the Sock Drawer Federation.",
  "Develop an education system for citizens of your imaginary bedroom nation.",
  "Create a social security system for retired items no longer in active use.",
  "Draft a constitution establishing fundamental pillow rights and sleeping freedoms.",
  "Write a bill of rights specifically protecting the right to nap without judgment.",

  // Performance reviews for body parts (426-450)
  "Conduct a comprehensive performance review for your knees, addressing recent complaints.",
  "Write a 360-degree feedback assessment for your hands from other body parts.",
  "Develop KPIs for your eyes and evaluate their quarterly performance.",
  "Perform a mid-year review for your back, setting goals for improved posture.",
  "Create a performance improvement plan for your stubborn left foot.",
  "Write a glowing review for your liver, acknowledging its thankless work.",
  "Develop a professional development plan for your ears, suggesting better listening skills.",
  "Perform an exit interview with your wisdom teeth before their departure.",
  "Create a promotion application for your dominant hand seeking more responsibility.",
  "Write a warning letter to your stomach about its disruptive behavior during meetings.",
  "Develop a mentorship program pairing experienced body parts with newer cells.",
  "Perform a performance review for your nose, addressing its tendency to run.",
  "Create a recognition award ceremony honoring body parts that exceeded expectations.",
  "Write a disciplinary action for your funny bone and its inappropriate timing.",
  "Develop an onboarding document for new grey hairs joining the team.",
  "Perform a team assessment of how well your left and right sides collaborate.",
  "Create a succession plan for when your hair follicles decide to retire.",
  "Write a performance review for your taste buds, noting their changing preferences.",
  "Develop compensation packages for body parts that work overtime (heart, lungs).",
  "Perform a skills assessment for your fingers, evaluating typing speed and dexterity.",
  "Create a wellness initiative for overworked body parts needing better work-life balance.",
  "Write a review for your immune system addressing recent performance issues.",
  "Develop a training program for your reflexes to improve response times.",
  "Perform an annual review for your brain, addressing memory performance concerns.",
  "Create employee of the month recognition for your most reliable body part.",

  // Hosting radio shows for no audience (451-475)
  "Create a morning radio show persona and broadcast to your empty kitchen with traffic updates.",
  "Develop a call-in advice show where you play both host and callers with different voices.",
  "Perform a late-night radio show in a whisper for your bedroom, featuring slow jams.",
  "Create a sports radio segment analyzing the athletic performance of your pets.",
  "Develop a conspiracy theory radio show broadcasting from your closet for security.",
  "Perform a classical music appreciation show, humming all the pieces yourself.",
  "Create a radio drama series performed entirely for an audience of houseplants.",
  "Develop a cooking show on radio, describing everything in unnecessary detail.",
  "Perform a radio DJ set using only sounds you can make with household items.",
  "Create a news radio station with updates on everything happening in your home.",
  "Develop a radio interview show where you interview yourself about interesting topics.",
  "Perform a radio game show where you're the host, contestants, and studio audience.",
  "Create a radio book club discussing whatever you're currently reading to no one.",
  "Develop a radio wellness show with meditation guidance for your bedroom.",
  "Perform a radio play with full sound effects and multiple character voices.",
  "Create a radio request show where you take imaginary requests and fulfill them.",
  "Develop a radio history show educating listeners about events in your household.",
  "Perform a radio technology show reviewing the appliances in your home.",
  "Create a radio relationship advice segment helping imaginary callers with problems.",
  "Develop a radio weather broadcast with detailed forecasts for individual rooms.",
  "Perform a radio mystery series with cliffhangers between episodes.",
  "Create a radio comedy hour featuring jokes and improvised comedy bits.",
  "Develop a radio documentary series investigating interesting household phenomena.",
  "Perform a radio astronomy show pointing out ceiling constellations to listeners.",
  "Create a radio gardening show for your houseplants to learn from.",

  // Creating choose-your-own-adventure for walking to the kitchen (476-500)
  "Write a choose-your-own-adventure where the path to the kitchen is fraught with danger.",
  "Develop multiple storylines for the epic quest of retrieving a glass of water.",
  "Create a branching narrative where each doorway presents a life-changing decision.",
  "Write a choose-your-own-adventure where the hallway contains a mysterious portal.",
  "Develop a story where you must negotiate with furniture guardians to reach the fridge.",
  "Create a romance subplot for your journey to the kitchen involving a charismatic plant.",
  "Write branching paths based on whether you turn left or right around the couch.",
  "Develop a choose-your-own-adventure with multiple endings based on snack choices.",
  "Create a mystery narrative where the kitchen holds clues to a greater conspiracy.",
  "Write a story where the journey to the kitchen spans multiple in-universe days.",
  "Develop a choose-your-own-adventure with a difficulty setting based on pet obstacles.",
  "Create a narrative where the hallway transforms into different biomes based on choices.",
  "Write branching storylines for encountering family members during your kitchen quest.",
  "Develop a story with resource management for the stamina needed to reach snacks.",
  "Create a choose-your-own-adventure where you can unlock secret rooms.",
  "Write a narrative where the refrigerator is a final boss requiring strategy to access.",
  "Develop multiple character classes for the kitchen journey with different abilities.",
  "Create a story with side quests available during the main kitchen objective.",
  "Write a choose-your-own-adventure with achievements for different journey choices.",
  "Develop a narrative with NPCs (pets, family) offering quests and rewards.",
  "Create a story where the kitchen represents a mythical location requiring trials to reach.",
  "Write branching paths based on the time of day affecting obstacles encountered.",
  "Develop a choose-your-own-adventure with good, bad, and secret endings.",
  "Create a narrative where previous kitchen journey choices affect future adventures.",
  "Write an epic saga where reaching the kitchen is just the beginning of the adventure."
];
